# Generated by Django 6.0.7 on 2026-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='City Hospital', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('currency', models.CharField(default='₹', max_length=5)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('date_format', models.CharField(default='d M Y', max_length=20)),
                ('footer', models.CharField(default='Hospital Management System', max_length=255)),
                ('about', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
